/**
 * Created by sabir on 19.07.17.
 */

export const LOAD_FORMS = 'LOAD_FORMS'
export const LOAD_FORMS_SUCCESS = 'LOAD_FORMS_SUCCESS'
export const LOAD_FORMS_FAIL = 'LOAD_FORMS_FAIL'

export const CREATE_FORM = 'CREATE_FORM'
export const CREATE_FORM_SUCCESS = 'CREATE_FORM_SUCCESS'
export const CREATE_FORM_FAIL = 'CREATE_FORM_FAIL'

export const UPDATE_FORM = 'UPDATE_FORM'
export const UPDATE_FORM_SUCCESS = 'UPDATE_FORM_SUCCESS'
export const UPDATE_FORM_FAIL = 'UPDATE_FORM_FAIL'

export const DELETE_FORM = 'DELETE_FORM'
export const DELETE_FORM_SUCCESS = 'DELETE_FORM_SUCCESS'
export const DELETE_FORM_FAIL = 'DELETE_FORM_FAIL'


export const LOAD_ORGANIZATIONS = 'LOAD_ORGANIZATIONS'
export const LOAD_ORGANIZATIONS_SUCCESS = 'LOAD_ORGANIZATIONS_SUCCESS'
export const LOAD_ORGANIZATIONS_FAIL = 'LOAD_ORGANIZATIONS_FAIL'
